// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Plum2: typeof import('./src/components/Plum2.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubNav: typeof import('./src/components/SubNav.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}

export {}
